### ISSUE TITLE
Unity plugin?

### ISSUE THREAD

**Issue by yosun** [LIFX/LIFXKit#29]
Not sure if this is a liftkit question exactly but can you guys put your Unity plugin on github or on your developer portal

**Comment by smarthall** [comment]
LIFX has not yet developed a plugin for Unity but it does sound like a really cool idea. We have released details on our LAN protocol so any developer should be able to build one now. You can read this documentation here: http://lan.developer.lifx.com/

If you do end up building one we would love to hear about it here: https://community.lifx.com/
